name: GameCI Template 🎮

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs: 
 checkLicense:
  name: check for unity licecnce
  runs-on: ubuntu-latest
  steps:
   - name: Fail - No License
     if: $({ !startsWith(env.UNITY_LICENSE, '<') })
     run: exit 1
